# Generated by Django 2.1.7 on 2019-02-23 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarDetails',
            fields=[
                ('carname', models.CharField(max_length=100)),
                ('cardetailsId', models.AutoField(primary_key=True, serialize=False)),
                ('carseats', models.IntegerField()),
                ('carNumber', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('name', models.CharField(max_length=250)),
                ('username', models.CharField(max_length=1000)),
                ('uniq_id', models.AutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(default='KIET123', max_length=250)),
                ('gender', models.CharField(max_length=250, null=True)),
                ('email', models.CharField(max_length=250, null=True)),
                ('mobile', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='startPooling',
            fields=[
                ('startPoolingId', models.AutoField(primary_key=True, serialize=False)),
                ('time_start', models.TimeField(blank=True, null=True)),
                ('time_end', models.TimeField(blank=True, null=True)),
                ('carPooled', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='login.CarDetails')),
            ],
        ),
        migrations.AddField(
            model_name='cardetails',
            name='addedBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='login.MyUser'),
        ),
    ]
