# Generated by Django 2.1.7 on 2019-02-23 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='startpooling',
            name='time_end',
        ),
        # migrations.AlterField(
        #     model_name='startpooling',
        #     name='time_start',
        #     field=models.IntegerField(null=True),
        # ),
    ]
