# Generated by Django 2.1.7 on 2019-02-23 22:23

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20190224_0337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startpooling',
            name='latitude',
            field=models.CharField(decimal_places=5, default=Decimal('0.0000'), max_digits=30),
        ),
        migrations.AlterField(
            model_name='startpooling',
            name='longitude',
            field=models.CharField(decimal_places=5, default=Decimal('0.0000'), max_digits=30),
        ),
    ]
