# Generated by Django 2.1.7 on 2019-02-23 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20190224_0353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startpooling',
            name='latitude',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='startpooling',
            name='longitude',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
