# Generated by Django 2.1.7 on 2019-02-24 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20190224_0355'),
    ]

    operations = [
        migrations.AddField(
            model_name='startpooling',
            name='seats',
            field=models.IntegerField(null=True),
        ),
    ]
