# Generated by Django 2.1.7 on 2019-02-24 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_auto_20190224_0948'),
    ]

    operations = [
        migrations.CreateModel(
            name='userPooling',
            fields=[
                ('userPoolingId', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=20, null=True)),
                ('userPooled', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='login.MyUser')),
            ],
        ),
    ]
