# Generated by Django 2.1.7 on 2019-02-24 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_userpooling'),
    ]

    operations = [
        migrations.AddField(
            model_name='startpooling',
            name='poolerid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='login.MyUser'),
        ),
    ]
