# Generated by Django 2.1.7 on 2019-02-24 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_startpooling_poolerid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='startpooling',
            name='poolerid',
        ),
    ]
