# Generated by Django 2.1.5 on 2019-02-23 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_signup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('name', models.CharField(max_length=250)),
                ('username', models.CharField(max_length=1000)),
                ('uniq_id', models.AutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(default='KIET123', max_length=250)),
                ('dob', models.DateField(null=True)),
                ('gender', models.CharField(max_length=250, null=True)),
                ('email', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
