# Generated by Django 2.1.5 on 2019-02-23 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_signup', '0002_auto_20190223_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='dob',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
