# Generated by Django 2.1.5 on 2019-02-23 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_signup', '0003_auto_20190223_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='mobile',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
