# Generated by Django 2.1.5 on 2019-02-23 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_signup', '0004_myuser_mobile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='dob',
        ),
    ]
