# Generated by Django 2.1.5 on 2019-02-23 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_signup', '0005_remove_myuser_dob'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarDetails',
            fields=[
                ('carname', models.CharField(max_length=100)),
                ('cardetailsId', models.AutoField(primary_key=True, serialize=False)),
                ('carseats', models.IntegerField(max_length=100)),
                ('carNumber', models.CharField(max_length=100)),
                ('addedBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='login_signup.MyUser')),
            ],
        ),
    ]
