# Generated by Django 2.1.7 on 2019-02-23 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_signup', '0008_auto_20190223_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardetails',
            name='carNumber2',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cardetails',
            name='addedBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login_signup.MyUser'),
        ),
    ]
