# Generated by Django 2.1.7 on 2019-02-23 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_signup', '0009_auto_20190223_1702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardetails',
            name='addedBy',
        ),
        migrations.RenameField(
            model_name='myuser',
            old_name='uniq_id',
            new_name='id',
        ),
        migrations.DeleteModel(
            name='CarDetails',
        ),
    ]
