# Generated by Django 2.1.7 on 2019-02-23 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_signup', '0010_auto_20190223_1707'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarDetails',
            fields=[
                ('carname', models.CharField(max_length=100)),
                ('cardetailsId', models.AutoField(primary_key=True, serialize=False)),
                ('carseats', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='myuser',
            old_name='id',
            new_name='uniq_id',
        ),
        migrations.AddField(
            model_name='cardetails',
            name='addedBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='login_signup.MyUser'),
        ),
    ]
