# Generated by Django 2.1.7 on 2019-02-23 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_signup', '0011_auto_20190223_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardetails',
            name='carNumber',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
