# Generated by Django 2.1.7 on 2019-02-23 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_signup', '0012_cardetails_carnumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='startPooling',
            fields=[
                ('startPoolingId', models.AutoField(primary_key=True, serialize=False)),
                ('time_start', models.TimeField(blank=True, null=True)),
                ('time_end', models.TimeField(blank=True, null=True)),
                ('carPooled', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='login_signup.CarDetails')),
            ],
        ),
    ]
